/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 1b3e8c985a882337475745a14a5a7d5e)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ResearchAgent";
	}
	interface Env {
		EMAIL: SendEmail;
		BROWSER: Fetcher;
		AI: Ai;
		EMAIL_FROM: string;
		ResearchAgent: DurableObjectNamespace<import("./src/server").ResearchAgent>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMAIL_FROM">> {}
}
